---
- name: Install Kubectl
  hosts: all
  tasks:
    - name: Check that the kubectl exists
      stat:
        path: /usr/local/bin/kubectl
      register: kubectl_exist
    - name: download kubectl
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: "/tmp/kubectl"
        mode: 0755
        timeout: 60
        force: false
        validate_certs: false
      tags: kubectl
      when: not kubectl_exist.stat.exists
    - name: install kubectl
      become: true
      file:
        src: "/tmp/kubectl"
        path: "/usr/local/bin/kubectl"
        state: hard
        mode: a+x
      tags: kubectl
      when: not kubectl_exist.stat.exists
- name: Install Minikube
  hosts: all
  tasks:
    - name: install docker
      become: true
      apt:
        name: docker.io
        update_cache: yes
      tags: minikube
    - name: install conntrack
      become: true
      apt:
        name: conntrack
        update_cache: yes
      tags: minikube
    - name: Check that the minikube exists
      stat:
        path: /usr/local/bin/minikube
      register: minikube_exist
    - name: download minikube
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        dest: "/tmp/minikube"
        mode: 0755
        timeout: 60
        force: false
        validate_certs: false
      tags: minikube
      when: not minikube_exist.stat.exists
    - name: install minikube
      become: true
      file:
        src: "/tmp/minikube"
        path: "/usr/local/bin/minikube"
        state: hard
        mode: a+x
      tags: minikube
      when: not minikube_exist.stat.exists
    - name: check the status of minikube.
      become: true
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
    - name: start minikube if it's not running.
      become: true
      command: minikube start --vm-driver=none
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
    - name: enable ingress addon
      become: true
      command: minikube addons enable ingress
- name: Deploy hello-world app
  hosts: all
  tasks:
    - name: install pip
      become: true
      apt:
        name: pip
        update_cache: yes
      tags: minikube
    - name: Install ansible kubernetes lib
      become: true
      pip:
        name: kubernetes
    - name: Create hello-world deployment
      become: true
      kubernetes.core.k8s:
        state: present
        template: 'hello-world-deployment.yaml.j2'
    - name: Create hello-world service
      become: true
      kubernetes.core.k8s:
        state: present
        template: 'hello-world-service.yaml.j2'
    - name: Create hello-world ingress
      become: true
      kubernetes.core.k8s:
        state: present
        template: 'hello-world-ingress.yaml.j2'
    - name: update hosts
      become: true
      command: sh -c "echo '10.128.0.3 hello-world.local' >> /etc/hosts"
